=== CenterForTheBuiltEnvironment/ABC_toolbox/json schema/abc-output-schema-V1.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "definitions": {
    "resultProperties": {
      "type": "object",
      "properties": {
        "comfort": {
          "type": "number",
          "description": "Thermal comfort. -4: Very uncomfortable, -2: uncomfortable, -0: XXX,  unit: dimensionless"
        },
        "comfort_weighted": {
          "type": "number",
          "description": "Weighted comfort score considering different factors."
        },
        "sensation": {
          "type": "number",
          "description": "Thermal sensation score."
        },
        "sensation_weighted": {
          "type": "number",
          "description": "Weighted thermal sensation score."
        },
        "tskin": {
          "type": "number",
          "description": "Skin temperature."
        },
        "tcore": {
          "type": "number",
          "description": "Core temperature."
        },
        "eht": {
          "type": "number",
          "description": "Effective heat transfer."
        },
        "ta": {
          "type": "number",
          "description": "Air temperature."
        },
        "rh": {
          "type": "number",
          "description": "Relative humidity."
        },
        "mrt": {
          "type": "number",
          "description": "Mean radiant temperature."
        },
        "v": {
          "type": "number",
          "description": "Air velocity."
        },
        "solar": {
          "type": "number",
          "description": "Solar radiation."
        },
        "q_met": {
          "type": "number",
          "description": "Metabolic heat production."
        },
        "q_conv": {
          "type": "number",
          "description": "Convective heat loss."
        },
        "q_rad": {
          "type": "number",
          "description": "Radiative heat loss."
        },
        "q_solar": {
          "type": "number",
          "description": "Heat gain from solar radiation."
        },
        "q_resp": {
          "type": "number",
          "description": "Respiratory heat loss."
        },
        "q_sweat": {
          "type": "number",
          "description": "Sweat evaporation heat loss."
        },
        "w": {
          "type": "number",
          "description": "Total skin wettedness."
        }
      }
    }
  },
  "properties": {
    "id": {
      "type": "integer",
      "description": "Unique identifier for the simulation.",
      "examples": [
        1
      ]
    },
    "name": {
      "type": "string",
      "description": "Name of the simulation."
    },
    "description": {
      "type": "string",
      "description": "Description of the simulation's purpose and setup."
    },
    "reference_time": {
      "type": "string",
      "description": "Timestamp for when the simulation results were generated, in ISO 8601 format."
    },
    "output_freq": {
      "type": "integer",
      "description": "Frequency at which data is output during the simulation, measured in seconds."
    },
    "comfort_model": {
      "type": "object",
      "description": "Configuration of the models used to assess comfort and sensation.",
      "properties": {
        "overall_sensation_model": {
          "type": "string",
          "description": "Model used for assessing overall sensation.",
          "default": "original",
          "enum": [
            "original",
            "weighted"
          ]
        },
        "local_sensation_model": {
          "type": "string",
          "description": "Model for assessing local sensation.",
          "default": "original",
          "enum": [
            "original",
            "weighted"
          ]
        },
        "overall_comfort_model": {
          "type": "string",
          "description": "Model for evaluating overall comfort.",
          "default": "original",
          "enum": [
            "original",
            "weighted"
          ]
        },
        "local_comfort_model": {
          "type": "string",
          "description": "Model for evaluating local comfort.",
          "default": "original",
          "enum": [
            "original",
            "weighted"
          ]
        },
        "segment_data": {
          "type": "object",
          "description": "Detailed parameters for each body segment influencing the comfort and sensation models.",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "C1_LTZero": {
                "type": "number",
                "description": "Static regression coefficient for local thermal sensation prediction model when skin temperature is lower than set-point (slope of logistic curve)."
              },
              "C1_GEZero": {
                "type": "number",
                "description": "Static regression coefficient for local thermal sensation prediction model when skin temperature is higher than set-point (slope of logistic curve)."
              },
              "K1_LTZero": {
                "type": "number",
                "description": "Factor for effect of whole-body temperature on local thermal sensation when skin temperature is lower than set-point."
              },
              "K1_GEZero": {
                "type": "number",
                "description": "Factor for effect of whole-body temperature on local thermal sensation when skin temperature is higher than set-point."
              },
              "C2_LTZero": {
                "type": "number",
                "description": "Dynamic regression coefficient of the local thermal sensation prediction model when skin temperature is lower than the set temperature."
              },
              "C2_GEZero": {
                "type": "number",
                "description": "Dynamic regression coefficient of the local thermal sensation prediction model when skin temperature is higher than set-point."
              },
              "C3": {
                "type": "number",
                "description": "Dynamic regression coefficient of the local thermal sensation prediction model when core temperature changes."
              },
              "C31": {
                "type": "number",
                "description": "Regression coefficient of the local thermal comfort prediction."
              },
              "C32": {
                "type": "number",
                "description": "Regression coefficient of the local thermal comfort prediction."
              },
              "C6": {
                "type": "number",
                "description": "Regression coefficient of the local thermal comfort prediction."
              },
              "C8": {
                "type": "number",
                "description": "Regression coefficient of the local thermal comfort prediction."
              },
              "C71": {
                "type": "number",
                "description": "Regression coefficient of the local thermal comfort prediction."
              },
              "C72": {
                "type": "number",
                "description": "Regression coefficient of the local thermal comfort prediction."
              },
              "TSL": {
                "type": "number",
                "description": "[???]"
              },
              "adaptationDeadband_negative": {
                "type": "number",
                "description": "[???] Negative range for adaptation deadband."
              },
              "adaptationDeadband_positive": {
                "type": "number",
                "description": "[???] Positive range for adaptation deadband."
              },
              "local_sensation_dominant_weight": {
                "type": "number",
                "description": "[???] Weight for local sensation in the overall comfort model."
              }
            }
          }
        }
      }
    },
    "results": {
      "type": "array",
      "description": "Array of simulation results",
      "properties": {
        "time": {
          "type": "integer",
          "description": "Simulation time at which the results were recorded, in seconds."
        },
        "met": {
          "type": "number",
          "description": "Metabolic rate at the recorded time, measured in met units."
        },
        "clo_ensemble_name": {
          "type": "string",
          "description": "Name of the clothing ensemble used during the simulation at this time."
        },
        "clo": {
          "type": "number",
          "description": "Clothing insulation value at the recorded time."
        },
        "overall": {
          "$ref": "#/definitions/resultProperties"
        },
        "segments": {
          "type": "object",
          "description": "Detailed segment-specific results for each body part.",
          "additionalProperties": {
            "$ref": "#/definitions/resultProperties"
          }
        }
      }
    },
    "simulation_version": {
      "type": "number",
      "description": "Version number of the simulation software."
    },
    "simulation_version_date": {
      "type": "string",
      "description": "Release date of the simulation software version."
    },
    "state": {
      "type": "object",
      "description": "Final state of the simulation, including temperatures and other state variables for each body segment."
    }
  }
}

=== CenterForTheBuiltEnvironment/ABC_toolbox/code/test_output.json
{
  "id": 1,
  "name": "Sample",
  "description": "This is a sample file.",
  "reference_time": "2024-02-07T02:31:28",
  "output_freq": 60,
  "comfort_model": {
    "overall_sensation_model": "original",
    "local_sensation_model": "original",
    "overall_comfort_model": "original",
    "local_comfort_model": "original",
    "segment_data": {
      "Head": {
        "C1_LTZero": 0.38,
        "C1_GEZero": 0.9,
        "K1_LTZero": 0.18,
        "K1_GEZero": 0.18,
        "C2_LTZero": 543.0,
        "C2_GEZero": 90.0,
        "C3": 0.0,
        "C31": -0.35,
        "C32": 0.35,
        "C6": 2.17,
        "C8": 0.5,
        "C71": 0.28,
        "C72": 0.4,
        "TSL": 0.6,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.5
      },
      "Chest": {
        "C1_LTZero": 0.35,
        "C1_GEZero": 1.0,
        "K1_LTZero": 0.1,
        "K1_GEZero": 0.1,
        "C2_LTZero": 39.0,
        "C2_GEZero": 136.0,
        "C3": -2135.0,
        "C31": -0.66,
        "C32": 0.66,
        "C6": 2.1,
        "C8": 0.0,
        "C71": 1.39,
        "C72": 0.9,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Back": {
        "C1_LTZero": 0.3,
        "C1_GEZero": 1.0,
        "K1_LTZero": 0.1,
        "K1_GEZero": 0.1,
        "C2_LTZero": 88.0,
        "C2_GEZero": 192.0,
        "C3": -4054.0,
        "C31": -0.45,
        "C32": 0.45,
        "C6": 2.1,
        "C8": 0.0,
        "C71": 0.96,
        "C72": 0.0,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Pelvis": {
        "C1_LTZero": 0.2,
        "C1_GEZero": 0.4,
        "K1_LTZero": 0.15,
        "K1_GEZero": 0.15,
        "C2_LTZero": 75.0,
        "C2_GEZero": 137.0,
        "C3": -5053.0,
        "C31": -0.59,
        "C32": 0.0,
        "C6": 2.06,
        "C8": -0.51,
        "C71": 0.5,
        "C72": 0.0,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Left Upper Arm": {
        "C1_LTZero": 0.29,
        "C1_GEZero": 0.4,
        "K1_LTZero": 0.1,
        "K1_GEZero": 0.1,
        "C2_LTZero": 156.0,
        "C2_GEZero": 167.0,
        "C3": 0.0,
        "C31": -0.3,
        "C32": 0.35,
        "C6": 2.14,
        "C8": -0.4,
        "C71": 0.0,
        "C72": 0.0,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Right Upper Arm": {
        "C1_LTZero": 0.29,
        "C1_GEZero": 0.4,
        "K1_LTZero": 0.1,
        "K1_GEZero": 0.1,
        "C2_LTZero": 156.0,
        "C2_GEZero": 167.0,
        "C3": 0.0,
        "C31": -0.3,
        "C32": 0.35,
        "C6": 2.14,
        "C8": -0.4,
        "C71": 0.0,
        "C72": 0.0,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Left Lower Arm": {
        "C1_LTZero": 0.3,
        "C1_GEZero": 0.7,
        "K1_LTZero": 0.1,
        "K1_GEZero": 0.1,
        "C2_LTZero": 144.0,
        "C2_GEZero": 125.0,
        "C3": 0.0,
        "C31": -0.23,
        "C32": 0.23,
        "C6": 2.0,
        "C8": -0.68,
        "C71": 0.0,
        "C72": 1.71,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.9,
        "adaptationDeadband_positive": 0.5,
        "local_sensation_dominant_weight": 0.0
      },
      "Right Lower Arm": {
        "C1_LTZero": 0.3,
        "C1_GEZero": 0.7,
        "K1_LTZero": 0.1,
        "K1_GEZero": 0.1,
        "C2_LTZero": 144.0,
        "C2_GEZero": 125.0,
        "C3": 0.0,
        "C31": -0.23,
        "C32": 0.23,
        "C6": 2.0,
        "C8": -0.68,
        "C71": 0.0,
        "C72": 1.71,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.9,
        "adaptationDeadband_positive": 0.5,
        "local_sensation_dominant_weight": 0.0
      },
      "Left Hand": {
        "C1_LTZero": 0.2,
        "C1_GEZero": 0.45,
        "K1_LTZero": 0.15,
        "K1_GEZero": 0.15,
        "C2_LTZero": 19.0,
        "C2_GEZero": 46.0,
        "C3": 0.0,
        "C31": -0.8,
        "C32": 0.8,
        "C6": 1.98,
        "C8": 0.0,
        "C71": 0.48,
        "C72": 0.48,
        "TSL": 0.075,
        "adaptationDeadband_negative": 2.1,
        "adaptationDeadband_positive": 1.4,
        "local_sensation_dominant_weight": 0.0
      },
      "Right Hand": {
        "C1_LTZero": 0.2,
        "C1_GEZero": 0.45,
        "K1_LTZero": 0.15,
        "K1_GEZero": 0.15,
        "C2_LTZero": 19.0,
        "C2_GEZero": 46.0,
        "C3": 0.0,
        "C31": -0.8,
        "C32": 0.8,
        "C6": 1.98,
        "C8": 0.0,
        "C71": 0.48,
        "C72": 0.48,
        "TSL": 0.075,
        "adaptationDeadband_negative": 2.1,
        "adaptationDeadband_positive": 1.4,
        "local_sensation_dominant_weight": 0.0
      },
      "Left Thigh": {
        "C1_LTZero": 0.2,
        "C1_GEZero": 0.29,
        "K1_LTZero": 0.11,
        "K1_GEZero": 0.11,
        "C2_LTZero": 151.0,
        "C2_GEZero": 263.0,
        "C3": 0.0,
        "C31": 0.0,
        "C32": 0.0,
        "C6": 1.98,
        "C8": 0.0,
        "C71": 0.0,
        "C72": 0.0,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Right Thigh": {
        "C1_LTZero": 0.2,
        "C1_GEZero": 0.29,
        "K1_LTZero": 0.11,
        "K1_GEZero": 0.11,
        "C2_LTZero": 151.0,
        "C2_GEZero": 263.0,
        "C3": 0.0,
        "C31": 0.0,
        "C32": 0.0,
        "C6": 1.98,
        "C8": 0.0,
        "C71": 0.0,
        "C72": 0.0,
        "TSL": 0.0,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Left Lower Leg": {
        "C1_LTZero": 0.29,
        "C1_GEZero": 0.4,
        "K1_LTZero": 0.1,
        "K1_GEZero": 0.1,
        "C2_LTZero": 206.0,
        "C2_GEZero": 212.0,
        "C3": 0.0,
        "C31": -0.2,
        "C32": 0.61,
        "C6": 2.0,
        "C8": 0.0,
        "C71": 1.67,
        "C72": 0.0,
        "TSL": 0.075,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Right Lower Leg": {
        "C1_LTZero": 0.29,
        "C1_GEZero": 0.4,
        "K1_LTZero": 0.1,
        "K1_GEZero": 0.1,
        "C2_LTZero": 206.0,
        "C2_GEZero": 212.0,
        "C3": 0.0,
        "C31": -0.2,
        "C32": 0.61,
        "C6": 2.0,
        "C8": 0.0,
        "C71": 1.67,
        "C72": 0.0,
        "TSL": 0.075,
        "adaptationDeadband_negative": 0.0,
        "adaptationDeadband_positive": 0.0,
        "local_sensation_dominant_weight": 0.0
      },
      "Left Foot": {
        "C1_LTZero": 0.25,
        "C1_GEZero": 0.26,
        "K1_LTZero": 0.15,
        "K1_GEZero": 0.15,
        "C2_LTZero": 109.0,
        "C2_GEZero": 162.0,
        "C3": 0.0,
        "C31": -0.91,
        "C32": 0.4,
        "C6": 2.13,
        "C8": 0.0,
        "C71": 0.5,
        "C72": 0.3,
        "TSL": 0.0,
        "adaptationDeadband_negative": 1.9,
        "adaptationDeadband_positive": 0.8,
        "local_sensation_dominant_weight": 0.0
      },
      "Right Foot": {
        "C1_LTZero": 0.25,
        "C1_GEZero": 0.26,
        "K1_LTZero": 0.15,
        "K1_GEZero": 0.15,
        "C2_LTZero": 109.0,
        "C2_GEZero": 162.0,
        "C3": 0.0,
        "C31": -0.91,
        "C32": 0.4,
        "C6": 2.13,
        "C8": 0.0,
        "C71": 0.5,
        "C72": 0.3,
        "TSL": 0.0,
        "adaptationDeadband_negative": 1.9,
        "adaptationDeadband_positive": 0.8,
        "local_sensation_dominant_weight": 0.0
      }
    }
  },
  "simulation_version": 0.1,
  "simulation_version_date": "Jun  9 2023 18:13:35",
  "results": [
    {
      "time": 59,
      "met": 1.0,
      "clo_ensemble_name": "sample_clothing_ensemble",
      "clo": 0.20000000000000007,
      "overall": {
        "comfort": 0.503270587364616,
        "comfort_weighted": 1.2080947841872616,
        "sensation": -0.43474571844335996,
        "sensation_linear": -0.1751383059964788,
        "sensation_weighted": -0.20194141423607195,
        "tskin": 33.521280298936865,
        "tneutral": 27.701172571943268,
        "tblood": 35.85687923557489,
        "pmv": -1.278521576607289,
        "ppd": 0.39168821410776106,
        "eht": 25.224561570220335,
        "ta": 25.000000000000004,
        "rh": 0.5,
        "mrt": 25.000000000000004,
        "v": 0.10000000000000003,
        "solar": 0.0,
        "q_met": 106.07876073126181,
        "q_conv": -44.87946370284568,
        "q_rad": -58.45047848818311,
        "q_solar": 0.0,
        "q_resp": -9.621141025004487,
        "q_sweat": -53.242858815254614
      },
      "segments": {
        "Head": {
          "tskin": 33.674143513410776,
          "tcore": 36.20124895095861,
          "eht": 24.798093292451924,
          "ta": 25.0,
          "mrt": 25.0,
          "v": 0.1,
          "rh": 0.5,
          "solar": 0.0,
          "q_met": 16.888739676047514,
          "q_conv": -3.6848945401655415,
          "q_rad": -4.56494375775029,
          "q_solar": 0.0,
          "q_resp": -0.0,
          "q_sweat": -4.505595074448825,
          "q_blood": -4.934093623310259,
          "q_blood_skin": 8.812110381995405,
          "skin_blood_flow": 4.032161609997162,
          "comfort": 2.5524276645572064,
          "comfort_weighted": 2.460516885486305,
          "sensation": -0.0433618561360527,
